# config.yaml
scanners:
  enabled_scanners:
    - iam
    - s3
    - ec2
    - rds
    - cloudfront
    - redshift
    - lambda
    - apigateway
  scan_interval: 3600  # 1 hour
  parallel_scans: 3
  timeout: 300  # 5 minutes

alerts:
  enabled: true
  alert_rules:
    - name: "Critical Security Issues"
      type: "risk_based"
      severity: "critical"
      risk_threshold: 9

    - name: "Compliance Violations"
      type: "compliance"
      severity: "high"
      frameworks:
        - "PCI-DSS"
        - "HIPAA"
        - "SOC2"

    - name: "Public Resource Alert"
      type: "custom"
      severity: "high"
      conditions:
        resource_type: "s3"
        public_access: true

notifications:
  slack:
    enabled: true
    webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
    channel: "#security-alerts"

  email:
    enabled: true
    sender: "security-scanner@example.com"
    recipients:
      - "security-team@example.com"
      - "cloud-admin@example.com"
    ses_region: "us-east-1"

  sns:
    enabled: true
    topic_arn: "arn:aws:sns:us-east-1:123456789012:security-alerts"

  security_hub:
    enabled: true
    region: "us-east-1"

reporting:
  enabled: true
  formats:
    - json
    - html
    - csv
  output_dir: "./reports"
  retention_days: 90
  include_summary: true
  include_trends: true

aws:
  regions:
    - us-east-1
    - us-west-2
    - eu-west-1
  role_arn: "arn:aws:iam::123456789012:role/SecurityScannerRole"
  external_id: "your-external-id"
  session_duration: 3600

logging:
  level: "INFO"
  file: "./aws-security-scanner.log"
  max_size: 10485760  # 10MB
  backup_count: 5

integrations:
  jira:
    enabled: false
    url: "https://your-jira-instance.atlassian.net"
    project_key: "SEC"
    issue_type: "Security Issue"

  servicenow:
    enabled: false
    instance: "your-instance"
    table: "incident"

  teams:
    enabled: false
    webhook_url: "https://outlook.office.com/webhook/..."

tags:
  environment: "production"
  owner: "security-team"
  project: "aws-security-scanner"
